version: '3'

services:
  mongo:
    image: mongo

  backend:
    build: backend
    restart: always
    labels:
      - "traefik.frontend.rule=Host:backend.docker.localhost"

  frontend:
    build: frontend
    labels:
      - "traefik.frontend.rule=Host:frontend.docker.localhost"

  proxy:
    image: traefik
    command: --docker # Tells Traefik to listen to docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
